apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-configmap
  namespace: roboshop
data:
  CART_HOST: "cart"
  CART_PORT: "8080"
  USER_HOST: "user"
  USER_PORT: "8080"
  AMQP_HOST: "rabbitmq"
  AMQP_USER: "roboshop"
  AMQP_PASS: "roboshop123"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: roboshop
  labels:
    name: roboshop
    env: dev
    running: payment
spec: 
  replicas: 1
  selector:
    matchLabels:
      name: roboshop
      env: dev
      running: payment
  template:
    metadata:
      labels:
        name: roboshop
        env: dev
        running: payment
    spec:
      containers:
      - name: payment
        image: balaji1729/payment:v1
        imagePullPolicy: Always
        ports:
        - name: liveness-port
          containerPort: 8080
        envFrom:
        - configMapRef:
            name: payment-configmap 
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 300m
            memory: 256Mi
        readinessProbe:
          httpGet:
            path: /health
            port: liveness-port
          failureThreshold: 1
          periodSeconds: 20
        livenessProbe:
          httpGet:
            path: /health
            port: liveness-port
          failureThreshold: 1
          periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: payment
  namespace: roboshop
spec:
  type: ClusterIP
  selector:
      name: roboshop
      env: dev
      running: payment
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: payment
  namespace: roboshop
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: payment
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 5